broker:
  cash: 10000.0
  commission: 0.0
data:
  symbol: ETHUSD
  start_date: 2026-06-24 17:00
  end_date: 2026-08-16 11:45
strategy:
  class: CrossSMAStrategy
  params:
    fast: 10
    slow: 30
sizer:
  type: percent
  params:
    percents: 95
